name: Publish PowerShell Module

on:

  release:

    types: [created]

jobs:

  publish-to-gallery:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build and publish

        env:

          NUGET_KEY: ${{ secrets.NUGET_KEY }}

        shell: pwsh

        run: |


          Publish-Module -Path ./app.ps1 -NuGetApiKey $env:NUGET_KEY -Verbose -Error-Action Retry
